# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/john/Desktop/adaptive sampling"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/john/Desktop/adaptive sampling"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/john/Desktop/adaptive sampling/CMakeFiles" "/home/john/Desktop/adaptive sampling//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/john/Desktop/adaptive sampling/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named raytracer

# Build rule for target.
raytracer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 raytracer
.PHONY : raytracer

# fast build rule for target.
raytracer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/build
.PHONY : raytracer/fast

src/Camera.o: src/Camera.cpp.o
.PHONY : src/Camera.o

# target to build an object file
src/Camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Camera.cpp.o
.PHONY : src/Camera.cpp.o

src/Camera.i: src/Camera.cpp.i
.PHONY : src/Camera.i

# target to preprocess a source file
src/Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Camera.cpp.i
.PHONY : src/Camera.cpp.i

src/Camera.s: src/Camera.cpp.s
.PHONY : src/Camera.s

# target to generate assembly for a file
src/Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Camera.cpp.s
.PHONY : src/Camera.cpp.s

src/DirectionalLight.o: src/DirectionalLight.cpp.o
.PHONY : src/DirectionalLight.o

# target to build an object file
src/DirectionalLight.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/DirectionalLight.cpp.o
.PHONY : src/DirectionalLight.cpp.o

src/DirectionalLight.i: src/DirectionalLight.cpp.i
.PHONY : src/DirectionalLight.i

# target to preprocess a source file
src/DirectionalLight.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/DirectionalLight.cpp.i
.PHONY : src/DirectionalLight.cpp.i

src/DirectionalLight.s: src/DirectionalLight.cpp.s
.PHONY : src/DirectionalLight.s

# target to generate assembly for a file
src/DirectionalLight.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/DirectionalLight.cpp.s
.PHONY : src/DirectionalLight.cpp.s

src/Light.o: src/Light.cpp.o
.PHONY : src/Light.o

# target to build an object file
src/Light.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Light.cpp.o
.PHONY : src/Light.cpp.o

src/Light.i: src/Light.cpp.i
.PHONY : src/Light.i

# target to preprocess a source file
src/Light.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Light.cpp.i
.PHONY : src/Light.cpp.i

src/Light.s: src/Light.cpp.s
.PHONY : src/Light.s

# target to generate assembly for a file
src/Light.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Light.cpp.s
.PHONY : src/Light.cpp.s

src/Material.o: src/Material.cpp.o
.PHONY : src/Material.o

# target to build an object file
src/Material.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Material.cpp.o
.PHONY : src/Material.cpp.o

src/Material.i: src/Material.cpp.i
.PHONY : src/Material.i

# target to preprocess a source file
src/Material.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Material.cpp.i
.PHONY : src/Material.cpp.i

src/Material.s: src/Material.cpp.s
.PHONY : src/Material.s

# target to generate assembly for a file
src/Material.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Material.cpp.s
.PHONY : src/Material.cpp.s

src/Mesh.o: src/Mesh.cpp.o
.PHONY : src/Mesh.o

# target to build an object file
src/Mesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Mesh.cpp.o
.PHONY : src/Mesh.cpp.o

src/Mesh.i: src/Mesh.cpp.i
.PHONY : src/Mesh.i

# target to preprocess a source file
src/Mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Mesh.cpp.i
.PHONY : src/Mesh.cpp.i

src/Mesh.s: src/Mesh.cpp.s
.PHONY : src/Mesh.s

# target to generate assembly for a file
src/Mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Mesh.cpp.s
.PHONY : src/Mesh.cpp.s

src/Ray.o: src/Ray.cpp.o
.PHONY : src/Ray.o

# target to build an object file
src/Ray.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Ray.cpp.o
.PHONY : src/Ray.cpp.o

src/Ray.i: src/Ray.cpp.i
.PHONY : src/Ray.i

# target to preprocess a source file
src/Ray.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Ray.cpp.i
.PHONY : src/Ray.cpp.i

src/Ray.s: src/Ray.cpp.s
.PHONY : src/Ray.s

# target to generate assembly for a file
src/Ray.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Ray.cpp.s
.PHONY : src/Ray.cpp.s

src/Scene.o: src/Scene.cpp.o
.PHONY : src/Scene.o

# target to build an object file
src/Scene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Scene.cpp.o
.PHONY : src/Scene.cpp.o

src/Scene.i: src/Scene.cpp.i
.PHONY : src/Scene.i

# target to preprocess a source file
src/Scene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Scene.cpp.i
.PHONY : src/Scene.cpp.i

src/Scene.s: src/Scene.cpp.s
.PHONY : src/Scene.s

# target to generate assembly for a file
src/Scene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Scene.cpp.s
.PHONY : src/Scene.cpp.s

src/Sphere.o: src/Sphere.cpp.o
.PHONY : src/Sphere.o

# target to build an object file
src/Sphere.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Sphere.cpp.o
.PHONY : src/Sphere.cpp.o

src/Sphere.i: src/Sphere.cpp.i
.PHONY : src/Sphere.i

# target to preprocess a source file
src/Sphere.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Sphere.cpp.i
.PHONY : src/Sphere.cpp.i

src/Sphere.s: src/Sphere.cpp.s
.PHONY : src/Sphere.s

# target to generate assembly for a file
src/Sphere.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Sphere.cpp.s
.PHONY : src/Sphere.cpp.s

src/Tempor.o: src/Tempor.cpp.o
.PHONY : src/Tempor.o

# target to build an object file
src/Tempor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Tempor.cpp.o
.PHONY : src/Tempor.cpp.o

src/Tempor.i: src/Tempor.cpp.i
.PHONY : src/Tempor.i

# target to preprocess a source file
src/Tempor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Tempor.cpp.i
.PHONY : src/Tempor.cpp.i

src/Tempor.s: src/Tempor.cpp.s
.PHONY : src/Tempor.s

# target to generate assembly for a file
src/Tempor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Tempor.cpp.s
.PHONY : src/Tempor.cpp.s

src/Texture.o: src/Texture.cpp.o
.PHONY : src/Texture.o

# target to build an object file
src/Texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Texture.cpp.o
.PHONY : src/Texture.cpp.o

src/Texture.i: src/Texture.cpp.i
.PHONY : src/Texture.i

# target to preprocess a source file
src/Texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Texture.cpp.i
.PHONY : src/Texture.cpp.i

src/Texture.s: src/Texture.cpp.s
.PHONY : src/Texture.s

# target to generate assembly for a file
src/Texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Texture.cpp.s
.PHONY : src/Texture.cpp.s

src/Triangle.o: src/Triangle.cpp.o
.PHONY : src/Triangle.o

# target to build an object file
src/Triangle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Triangle.cpp.o
.PHONY : src/Triangle.cpp.o

src/Triangle.i: src/Triangle.cpp.i
.PHONY : src/Triangle.i

# target to preprocess a source file
src/Triangle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Triangle.cpp.i
.PHONY : src/Triangle.cpp.i

src/Triangle.s: src/Triangle.cpp.s
.PHONY : src/Triangle.s

# target to generate assembly for a file
src/Triangle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Triangle.cpp.s
.PHONY : src/Triangle.cpp.s

src/accelerate.o: src/accelerate.cpp.o
.PHONY : src/accelerate.o

# target to build an object file
src/accelerate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/accelerate.cpp.o
.PHONY : src/accelerate.cpp.o

src/accelerate.i: src/accelerate.cpp.i
.PHONY : src/accelerate.i

# target to preprocess a source file
src/accelerate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/accelerate.cpp.i
.PHONY : src/accelerate.cpp.i

src/accelerate.s: src/accelerate.cpp.s
.PHONY : src/accelerate.s

# target to generate assembly for a file
src/accelerate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/accelerate.cpp.s
.PHONY : src/accelerate.cpp.s

src/handle_events.o: src/handle_events.cpp.o
.PHONY : src/handle_events.o

# target to build an object file
src/handle_events.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/handle_events.cpp.o
.PHONY : src/handle_events.cpp.o

src/handle_events.i: src/handle_events.cpp.i
.PHONY : src/handle_events.i

# target to preprocess a source file
src/handle_events.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/handle_events.cpp.i
.PHONY : src/handle_events.cpp.i

src/handle_events.s: src/handle_events.cpp.s
.PHONY : src/handle_events.s

# target to generate assembly for a file
src/handle_events.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/handle_events.cpp.s
.PHONY : src/handle_events.cpp.s

src/hdr.o: src/hdr.cpp.o
.PHONY : src/hdr.o

# target to build an object file
src/hdr.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/hdr.cpp.o
.PHONY : src/hdr.cpp.o

src/hdr.i: src/hdr.cpp.i
.PHONY : src/hdr.i

# target to preprocess a source file
src/hdr.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/hdr.cpp.i
.PHONY : src/hdr.cpp.i

src/hdr.s: src/hdr.cpp.s
.PHONY : src/hdr.s

# target to generate assembly for a file
src/hdr.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/hdr.cpp.s
.PHONY : src/hdr.cpp.s

src/intersect.o: src/intersect.cpp.o
.PHONY : src/intersect.o

# target to build an object file
src/intersect.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/intersect.cpp.o
.PHONY : src/intersect.cpp.o

src/intersect.i: src/intersect.cpp.i
.PHONY : src/intersect.i

# target to preprocess a source file
src/intersect.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/intersect.cpp.i
.PHONY : src/intersect.cpp.i

src/intersect.s: src/intersect.cpp.s
.PHONY : src/intersect.s

# target to generate assembly for a file
src/intersect.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/intersect.cpp.s
.PHONY : src/intersect.cpp.s

src/objects.o: src/objects.cpp.o
.PHONY : src/objects.o

# target to build an object file
src/objects.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/objects.cpp.o
.PHONY : src/objects.cpp.o

src/objects.i: src/objects.cpp.i
.PHONY : src/objects.i

# target to preprocess a source file
src/objects.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/objects.cpp.i
.PHONY : src/objects.cpp.i

src/objects.s: src/objects.cpp.s
.PHONY : src/objects.s

# target to generate assembly for a file
src/objects.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/objects.cpp.s
.PHONY : src/objects.cpp.s

src/parse_image.o: src/parse_image.cpp.o
.PHONY : src/parse_image.o

# target to build an object file
src/parse_image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/parse_image.cpp.o
.PHONY : src/parse_image.cpp.o

src/parse_image.i: src/parse_image.cpp.i
.PHONY : src/parse_image.i

# target to preprocess a source file
src/parse_image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/parse_image.cpp.i
.PHONY : src/parse_image.cpp.i

src/parse_image.s: src/parse_image.cpp.s
.PHONY : src/parse_image.s

# target to generate assembly for a file
src/parse_image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/parse_image.cpp.s
.PHONY : src/parse_image.cpp.s

src/parse_lights.o: src/parse_lights.cpp.o
.PHONY : src/parse_lights.o

# target to build an object file
src/parse_lights.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/parse_lights.cpp.o
.PHONY : src/parse_lights.cpp.o

src/parse_lights.i: src/parse_lights.cpp.i
.PHONY : src/parse_lights.i

# target to preprocess a source file
src/parse_lights.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/parse_lights.cpp.i
.PHONY : src/parse_lights.cpp.i

src/parse_lights.s: src/parse_lights.cpp.s
.PHONY : src/parse_lights.s

# target to generate assembly for a file
src/parse_lights.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/parse_lights.cpp.s
.PHONY : src/parse_lights.cpp.s

src/parse_transformation.o: src/parse_transformation.cpp.o
.PHONY : src/parse_transformation.o

# target to build an object file
src/parse_transformation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/parse_transformation.cpp.o
.PHONY : src/parse_transformation.cpp.o

src/parse_transformation.i: src/parse_transformation.cpp.i
.PHONY : src/parse_transformation.i

# target to preprocess a source file
src/parse_transformation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/parse_transformation.cpp.i
.PHONY : src/parse_transformation.cpp.i

src/parse_transformation.s: src/parse_transformation.cpp.s
.PHONY : src/parse_transformation.s

# target to generate assembly for a file
src/parse_transformation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/parse_transformation.cpp.s
.PHONY : src/parse_transformation.cpp.s

src/ply_parser.o: src/ply_parser.cpp.o
.PHONY : src/ply_parser.o

# target to build an object file
src/ply_parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/ply_parser.cpp.o
.PHONY : src/ply_parser.cpp.o

src/ply_parser.i: src/ply_parser.cpp.i
.PHONY : src/ply_parser.i

# target to preprocess a source file
src/ply_parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/ply_parser.cpp.i
.PHONY : src/ply_parser.cpp.i

src/ply_parser.s: src/ply_parser.cpp.s
.PHONY : src/ply_parser.s

# target to generate assembly for a file
src/ply_parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/ply_parser.cpp.s
.PHONY : src/ply_parser.cpp.s

src/ppm.o: src/ppm.cpp.o
.PHONY : src/ppm.o

# target to build an object file
src/ppm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/ppm.cpp.o
.PHONY : src/ppm.cpp.o

src/ppm.i: src/ppm.cpp.i
.PHONY : src/ppm.i

# target to preprocess a source file
src/ppm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/ppm.cpp.i
.PHONY : src/ppm.cpp.i

src/ppm.s: src/ppm.cpp.s
.PHONY : src/ppm.s

# target to generate assembly for a file
src/ppm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/ppm.cpp.s
.PHONY : src/ppm.cpp.s

src/raytracer.o: src/raytracer.cpp.o
.PHONY : src/raytracer.o

# target to build an object file
src/raytracer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/raytracer.cpp.o
.PHONY : src/raytracer.cpp.o

src/raytracer.i: src/raytracer.cpp.i
.PHONY : src/raytracer.i

# target to preprocess a source file
src/raytracer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/raytracer.cpp.i
.PHONY : src/raytracer.cpp.i

src/raytracer.s: src/raytracer.cpp.s
.PHONY : src/raytracer.s

# target to generate assembly for a file
src/raytracer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/raytracer.cpp.s
.PHONY : src/raytracer.cpp.s

src/read_array.o: src/read_array.cpp.o
.PHONY : src/read_array.o

# target to build an object file
src/read_array.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/read_array.cpp.o
.PHONY : src/read_array.cpp.o

src/read_array.i: src/read_array.cpp.i
.PHONY : src/read_array.i

# target to preprocess a source file
src/read_array.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/read_array.cpp.i
.PHONY : src/read_array.cpp.i

src/read_array.s: src/read_array.cpp.s
.PHONY : src/read_array.s

# target to generate assembly for a file
src/read_array.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/read_array.cpp.s
.PHONY : src/read_array.cpp.s

src/sendray.o: src/sendray.cpp.o
.PHONY : src/sendray.o

# target to build an object file
src/sendray.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/sendray.cpp.o
.PHONY : src/sendray.cpp.o

src/sendray.i: src/sendray.cpp.i
.PHONY : src/sendray.i

# target to preprocess a source file
src/sendray.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/sendray.cpp.i
.PHONY : src/sendray.cpp.i

src/sendray.s: src/sendray.cpp.s
.PHONY : src/sendray.s

# target to generate assembly for a file
src/sendray.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/sendray.cpp.s
.PHONY : src/sendray.cpp.s

src/sphere2d.o: src/sphere2d.cpp.o
.PHONY : src/sphere2d.o

# target to build an object file
src/sphere2d.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/sphere2d.cpp.o
.PHONY : src/sphere2d.cpp.o

src/sphere2d.i: src/sphere2d.cpp.i
.PHONY : src/sphere2d.i

# target to preprocess a source file
src/sphere2d.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/sphere2d.cpp.i
.PHONY : src/sphere2d.cpp.i

src/sphere2d.s: src/sphere2d.cpp.s
.PHONY : src/sphere2d.s

# target to generate assembly for a file
src/sphere2d.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/sphere2d.cpp.s
.PHONY : src/sphere2d.cpp.s

src/submit.o: src/submit.cpp.o
.PHONY : src/submit.o

# target to build an object file
src/submit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/submit.cpp.o
.PHONY : src/submit.cpp.o

src/submit.i: src/submit.cpp.i
.PHONY : src/submit.i

# target to preprocess a source file
src/submit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/submit.cpp.i
.PHONY : src/submit.cpp.i

src/submit.s: src/submit.cpp.s
.PHONY : src/submit.s

# target to generate assembly for a file
src/submit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/submit.cpp.s
.PHONY : src/submit.cpp.s

src/test.o: src/test.cpp.o
.PHONY : src/test.o

# target to build an object file
src/test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/test.cpp.o
.PHONY : src/test.cpp.o

src/test.i: src/test.cpp.i
.PHONY : src/test.i

# target to preprocess a source file
src/test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/test.cpp.i
.PHONY : src/test.cpp.i

src/test.s: src/test.cpp.s
.PHONY : src/test.s

# target to generate assembly for a file
src/test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/test.cpp.s
.PHONY : src/test.cpp.s

src/vector.o: src/vector.cpp.o
.PHONY : src/vector.o

# target to build an object file
src/vector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/vector.cpp.o
.PHONY : src/vector.cpp.o

src/vector.i: src/vector.cpp.i
.PHONY : src/vector.i

# target to preprocess a source file
src/vector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/vector.cpp.i
.PHONY : src/vector.cpp.i

src/vector.s: src/vector.cpp.s
.PHONY : src/vector.s

# target to generate assembly for a file
src/vector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/vector.cpp.s
.PHONY : src/vector.cpp.s

src/x_utilities.o: src/x_utilities.cpp.o
.PHONY : src/x_utilities.o

# target to build an object file
src/x_utilities.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/x_utilities.cpp.o
.PHONY : src/x_utilities.cpp.o

src/x_utilities.i: src/x_utilities.cpp.i
.PHONY : src/x_utilities.i

# target to preprocess a source file
src/x_utilities.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/x_utilities.cpp.i
.PHONY : src/x_utilities.cpp.i

src/x_utilities.s: src/x_utilities.cpp.s
.PHONY : src/x_utilities.s

# target to generate assembly for a file
src/x_utilities.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/x_utilities.cpp.s
.PHONY : src/x_utilities.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... raytracer"
	@echo "... src/Camera.o"
	@echo "... src/Camera.i"
	@echo "... src/Camera.s"
	@echo "... src/DirectionalLight.o"
	@echo "... src/DirectionalLight.i"
	@echo "... src/DirectionalLight.s"
	@echo "... src/Light.o"
	@echo "... src/Light.i"
	@echo "... src/Light.s"
	@echo "... src/Material.o"
	@echo "... src/Material.i"
	@echo "... src/Material.s"
	@echo "... src/Mesh.o"
	@echo "... src/Mesh.i"
	@echo "... src/Mesh.s"
	@echo "... src/Ray.o"
	@echo "... src/Ray.i"
	@echo "... src/Ray.s"
	@echo "... src/Scene.o"
	@echo "... src/Scene.i"
	@echo "... src/Scene.s"
	@echo "... src/Sphere.o"
	@echo "... src/Sphere.i"
	@echo "... src/Sphere.s"
	@echo "... src/Tempor.o"
	@echo "... src/Tempor.i"
	@echo "... src/Tempor.s"
	@echo "... src/Texture.o"
	@echo "... src/Texture.i"
	@echo "... src/Texture.s"
	@echo "... src/Triangle.o"
	@echo "... src/Triangle.i"
	@echo "... src/Triangle.s"
	@echo "... src/accelerate.o"
	@echo "... src/accelerate.i"
	@echo "... src/accelerate.s"
	@echo "... src/handle_events.o"
	@echo "... src/handle_events.i"
	@echo "... src/handle_events.s"
	@echo "... src/hdr.o"
	@echo "... src/hdr.i"
	@echo "... src/hdr.s"
	@echo "... src/intersect.o"
	@echo "... src/intersect.i"
	@echo "... src/intersect.s"
	@echo "... src/objects.o"
	@echo "... src/objects.i"
	@echo "... src/objects.s"
	@echo "... src/parse_image.o"
	@echo "... src/parse_image.i"
	@echo "... src/parse_image.s"
	@echo "... src/parse_lights.o"
	@echo "... src/parse_lights.i"
	@echo "... src/parse_lights.s"
	@echo "... src/parse_transformation.o"
	@echo "... src/parse_transformation.i"
	@echo "... src/parse_transformation.s"
	@echo "... src/ply_parser.o"
	@echo "... src/ply_parser.i"
	@echo "... src/ply_parser.s"
	@echo "... src/ppm.o"
	@echo "... src/ppm.i"
	@echo "... src/ppm.s"
	@echo "... src/raytracer.o"
	@echo "... src/raytracer.i"
	@echo "... src/raytracer.s"
	@echo "... src/read_array.o"
	@echo "... src/read_array.i"
	@echo "... src/read_array.s"
	@echo "... src/sendray.o"
	@echo "... src/sendray.i"
	@echo "... src/sendray.s"
	@echo "... src/sphere2d.o"
	@echo "... src/sphere2d.i"
	@echo "... src/sphere2d.s"
	@echo "... src/submit.o"
	@echo "... src/submit.i"
	@echo "... src/submit.s"
	@echo "... src/test.o"
	@echo "... src/test.i"
	@echo "... src/test.s"
	@echo "... src/vector.o"
	@echo "... src/vector.i"
	@echo "... src/vector.s"
	@echo "... src/x_utilities.o"
	@echo "... src/x_utilities.i"
	@echo "... src/x_utilities.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

